=== lhuarcayat/BedrockAgent/notebook/shared/evaluation_type/RUB/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "RUB_DIAN",
  "type": "object",
  "properties": {
    "companyName": {
      "type": "string",
      "description": "Razón Social de la persona o entidad beneficiaria"
    },
    "documentType": {
      "type": "string",
      "description": "Document name for identify the company (NIT, RUC) or identication number type (ej. 1)"
    },
    "country": {
      "type": "string",
      "description": "País de la empresa"
    },
    "taxId": {
      "type": "string",
      "pattern": "^[0-9.\\-]+$",
      "description": "Número de Identificación Tributaria (NIT)"
    },
    "relatedParties": {
      "type": "array",
      "description": "Listado de personas relacionadas con el beneficiario",
      "items": {
        "type": "object",
        "properties": {
          "firstName": {
            "type": "string",
            "description": "Nombre de la persona relacionada"
          },
          "lastName": {
            "type": "string",
            "description": "Apellido de la persona relacionada"
          },
          "identificationType": {
            "type": "string",
            "description": "Tipo de identificación de la persona (ej. Cédula de Ciudadanía)"
          },
          "identificationNumber": {
            "type": "string",
            "description": "Número de identificación de la persona relacionada"
          },
          "noveltyType": {
            "type": "string",
            "description": "Tipo de novedad reportada en el RUB (ej. Registro, Alta, Modificación, Baja)"
          },
          "participationPercentage": {
            "type": "string",
            "pattern": "^[0-9]+(\\.[0-9]+)?$",
            "description": "Porcentaje de participación (número, sin símbolo “%”)"
          },
          "message": {
            "type": "string",
            "description": "Mensaje de evaluacion si documento evaluado no corresponde a documento oficial"
          }
        }
      },
      "required": [
        "firstName",
        "lastName",
        "identificationType",
        "identificationNumber",
        "noveltyType",
        "participationPercentage"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "companyName",
    "documentType",
    "taxId",
    "relatedParties"
  ],
  "additionalProperties": false
}

=== lhuarcayat/BedrockAgent/notebook/extraction-scoring/src/outputs/extraction/RUT/exec_v0/vllama_scout_v_0/payload_vllama_scout_v_0.json
{
  "companyName": "FARMACIA INSTITUCIONAL S A S",
  "documentType": "NIT",
  "taxId": "14699744621",
  "relatedParties": [
    {
      "identificationType": "Cédula de Ciudadanía",
      "identificationNumber": "1380230151",
      "relationshipType": "REPRS LEGAL PRIN",
      "firstName": "TOVAR",
      "lastName": "OSORIO LEON ALEXANDER"
    },
    {
      "identificationType": "Cédula de Ciudadanía",
      "identificationNumber": "5205335354",
      "relationshipType": "REPRS LEGAL SUPL",
      "firstName": "OLGA LUCIA",
      "lastName": "RUGE TOVAR"
    },
    {
      "identificationType": "Cédula de Ciudadanía",
      "identificationNumber": "79474741",
      "relationshipType": "Contador",
      "firstName": "MARIA DEL CARMEN",
      "lastName": "VALDERRAMA ESQUIVEL WILIAN ANDRES"
    },
    {
      "identificationType": "Cédula de Ciudadanía",
      "identificationNumber": "1379663905",
      "relationshipType": "Revisor Fiscal Principal",
      "firstName": "MILCIADES",
      "lastName": "TAPIAS MENDIETA"
    }
  ],
  "country": "COLOMBIA"
}

=== lhuarcayat/BedrockAgent/notebook/extraction-scoring/src/outputs/extraction/RUB/exec_v1/vllama_mav_v_1/payload_vllama_mav_v_1.json
{
  "companyName": "G4S SECURE SOLUTIONS COLOMBIA S A",
  "documentType": "NIT",
  "taxId": "860013951",
  "relatedParties": [
    {
      "firstName": "DAVID ISAAC",
      "lastName": "BUCKMAN",
      "identificationType": "Cédula de Extranjería",
      "identificationNumber": "19740758",
      "noveltyType": "Registro",
      "participationPercentage": "0"
    }
  ],
  "country": "Colombia"
}

=== lhuarcayat/BedrockAgent/notebook/extraction-scoring/src/outputs/extraction/CERL/prompt_txt/vllama_3_v1/payload_vllama_3_v1.json
{
  "companyName": "GEOKINETICS INTERNACIONAL, INC.",
  "documentType": "NIT",
  "taxId": "860006152-8",
  "relatedParties": [
    {
      "firstName": "NARCISO",
      "lastName": "IVANUEL CHIQUILLO CONDE",
      "identificationType": "C.C.",
      "identificationNumber": "17124736",
      "relationshipType": "Representante Legal"
    },
    {
      "firstName": "JORGE",
      "lastName": "RODRIGUEZ ROJAS",
      "identificationType": "C.C.",
      "identificationNumber": "1744414",
      "relationshipType": "Apoderado General"
    },
    {
      "firstName": "JOSE",
      "lastName": "MANUEL TAMAYO OLARTE",
      "identificationType": "C.C.",
      "identificationNumber": "19303534",
      "relationshipType": "Apoderado General"
    },
    {
      "firstName": "VICTOR",
      "lastName": "URCICIO GOMEZ GUTIERREZ",
      "identificationType": "C.C.",
      "identificationNumber": "8041476",
      "relationshipType": "Apoderado General"
    },
    {
      "firstName": "RAFAEL",
      "lastName": "CASILLO CHARRY",
      "identificationType": "C.C.",
      "identificationNumber": "79370170",
      "relationshipType": "Apoderado General"
    },
    {
      "companyName": "ERNST & YOUNG AUDIT LTDA",
      "identificationType": "",
      "identificationNumber": "000008600088905",
      "relationshipType": "Revisor Fiscal"
    },
    {
      "firstName": "FABIO",
      "lastName": "MONTAÑELEGRE BUENAÑA",
      "identificationType": "C.C.",
      "identificationNumber": "36373989",
      "relationshipType": "Revisor Fiscal"
    }
  ],
  "country": "COLOMBIA"
}

=== lhuarcayat/BedrockAgent/notebook/extraction-scoring/src/outputs/extraction/RUB/exec_v3/vllama_mav_v_3/payload_vllama_mav_v_3.json
{
  "companyName": "PAR SERVICIOS INTEGRALES S A",
  "documentType": "NIT",
  "taxId": "830067329",
  "relatedParties": [
    {
      "firstName": "ANDRES LEONARDO",
      "lastName": "RODRIGUEZ RAMIREZ",
      "identificationType": "Cédula de Ciudadanía",
      "identificationNumber": "80074122",
      "noveltyType": "Registro",
      "participationPercentage": "14.99"
    },
    {
      "firstName": "LUIS ALBERTO",
      "lastName": "RODRIGUEZ SAMUDIO",
      "identificationType": "Cédula de Ciudadanía",
      "identificationNumber": "19193304",
      "noveltyType": "Registro",
      "participationPercentage": "29.98"
    },
    {
      "firstName": "DIANA PAOLA",
      "lastName": "RODRIGUEZ RAMIREZ",
      "identificationType": "Cédula de Ciudadanía",
      "identificationNumber": "52817177",
      "noveltyType": "Registro",
      "participationPercentage": "14.99"
    },
    {
      "firstName": "ESTEFANIA",
      "lastName": "CORREDOR RODRIGUEZ",
      "identificationType": "Cédula de Ciudadanía",
      "identificationNumber": "1019026903",
      "noveltyType": "Registro",
      "participationPercentage": "5.02"
    },
    {
      "firstName": "LUIS MIGUEL",
      "lastName": "ZUBIETA URIBE",
      "identificationType": "Cédula de Ciudadanía",
      "identificationNumber": "79939362",
      "noveltyType": "Registro",
      "participationPercentage": "14.99"
    },
    {
      "firstName": "CAROLINA",
      "lastName": "CORREDOR RODRIGUEZ",
      "identificationType": "Cédula de Ciudadanía",
      "identificationNumber": "52799584",
      "noveltyType": "Registro",
      "participationPercentage": "5.02"
    },
    {
      "firstName": "ENRIQUE",
      "lastName": "MERCADO IDARRAGA",
      "identificationType": "Cédula de Ciudadanía",
      "identificationNumber": "80134782",
      "noveltyType": "Registro",
      "participationPercentage": "10.05"
    }
  ],
  "country": "Colombia"
}

=== lhuarcayat/BedrockAgent/notebook/extraction-scoring/src/outputs/extraction/CERL/prompt_txt/exec_v3/vllama_scout_v_1/payload_vllama_scout_v_1.json
{
  "companyName": "GEOINTNETICS INTERNATIONAL, INC.",
  "documentType": "Certificado de Existencia y Representación Legal",
  "taxId": "860006152-8",
  "relatedParties": [
    {
      "firstName": "Jorge Enrique",
      "lastName": "Rodriguez Rojas",
      "identificationType": "C.C.",
      "identificationNumber": "000000017144874",
      "relationshipType": "Primer Suplente del Apoderado General Principal"
    },
    {
      "firstName": "Narciso Manuel",
      "lastName": "Chiquillo Conde",
      "identificationType": "Cédula de Ciudadanía",
      "identificationNumber": "17.124.736",
      "relationshipType": "Representante Legal"
    }
  ],
  "country": "Colombia"
}

=== lhuarcayat/BedrockAgent/notebook/extraction-scoring/src/outputs/extraction/prompt_txt/v15/payload_v15.json
{
  "companyName": "AEROSUPPORT S.A.S.",
  "documentType": "NIT",
  "taxId": "800.216.686-2",
  "relatedParties": [
    {
      "companyName": "GERMAN SALGADO VERGARA",
      "identificationType": "C.C.",
      "identificationNumber": "19.306.991",
      "relationshipType": "Shareholder",
      "participationPercentage": "49.50"
    },
    {
      "companyName": "GLOBAL AVIATION SUPPORT CORP",
      "identificationType": "NIT",
      "identificationNumber": "1045179-1-546162",
      "relationshipType": "Shareholder",
      "participationPercentage": "49.00"
    },
    {
      "firstName": "ADRIANA",
      "lastName": "ARANGO JARAMILLO",
      "identificationType": "C.C.",
      "identificationNumber": "35469632",
      "relationshipType": "Shareholder",
      "participationPercentage": "1.00"
    },
    {
      "companyName": "NICOLAS SALGADO ARANGO",
      "identificationType": "C.C.",
      "identificationNumber": "1020763136",
      "relationshipType": "Shareholder",
      "participationPercentage": "0.50"
    }
  ]
}

=== lhuarcayat/BedrockAgent/notebook/extraction-scoring/src/outputs/extraction/CERL/prompt_txt/exec_v3/vllama_mav_v_1/payload_vllama_mav_v_1.json
{
  "companyName": "GEOKINETICS INTERNATIONAL, INC.",
  "documentType": "NIT",
  "taxId": "860006152-8",
  "relatedParties": [
    {
      "firstName": "Jorge Enrique",
      "lastName": "Rodriguez Rojas",
      "identificationType": "C.C.",
      "identificationNumber": "17448874",
      "relationshipType": "Apoderado General Principal"
    },
    {
      "firstName": "Narciso Manuel",
      "lastName": "Chiquillo Conde",
      "identificationType": "C.C.",
      "identificationNumber": "17124736",
      "relationshipType": "Representante Legal"
    },
    {
      "firstName": "Maria Magdalena",
      "lastName": "Falla Montealegre Buistamante",
      "identificationType": "C.C.",
      "identificationNumber": "36372389",
      "relationshipType": "Revisor Fiscal Principal"
    }
  ],
  "country": "Colombia"
}
